# Generated by Django 4.2.7 on 2023-11-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_userurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
