# Generated by Django 4.2.7 on 2023-11-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_userstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='click_count')),
            ],
            options={
                'verbose_name': 'URL click',
                'verbose_name_plural': 'URL clicks',
            },
        ),
    ]
