# Generated by Django 4.2.7 on 2023-11-17 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0008_click_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість кліків'),
        ),
        migrations.AlterField(
            model_name='click',
            name='url',
            field=models.URLField(unique=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='click',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='userurl',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.DeleteModel(
            name='UserStatistic',
        ),
    ]
